name: CI
on:
  push:
      branches:
          - master
      tags:
          - v*
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        run: ./gradlew check
      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports-build
          path: '**/build/reports'
      - name: Upload analysis to sonarcloud
        if: "${{ env.SONAR_TOKEN != '' }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew sonarqube -Dsonar.projectKey=xenit-eu_alfresco-remote-testrunner -Dsonar.organization=xenit-eu -Dsonar.host.url=https://sonarcloud.io
  publish:
    runs-on: ubuntu-latest
    needs: check
    if: "${{ github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master') }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish
        env:
          SIGNING_PRIVATE_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          SIGNING_PASSWORD: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

          ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.GRADLE_PLUGINS_PUBLISH_KEY }}
          ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.GRADLE_PLUGINS_PUBLISH_SECRET }}
        run: ./gradlew publish publishPlugins
